language: c
sudo: required
dist: trusty
os:
  - linux
  - osx
branches:
  except:
    - master
    - /^(wip\/)?(appveyor|msvc|windows)(\-.+)?$/
env:
  matrix:
    - COMPILER=clang
    # - COMPILER=clang-3.7
    # - COMPILER=clang-3.5 CFLAGS="-fsanitize=address -fsanitize=undefined"
    # - COMPILER=clang-3.4 CFLAGS="-fsanitize=address -fsanitize=undefined"
    - COMPILER=gcc-6 UBSAN=y
    - COMPILER=gcc-5 CSTD=11 UBSAN=y
    - COMPILER=gcc-4.9 ASAN=y UBSAN=y
    - COMPILER=clang-3.6 ASAN=y UBSAN=y
    - COMPILER=gcc-4.8 ASAN=y
    - COMPILER=gcc-4.6
    - COMPILER=gcc-4.4
    - COMPILER=x86_64-w64-mingw32-gcc EXTENSION=".exe"
    - COMPILER=i686-w64-mingw32-gcc EXTENSION=".exe"
    - COMPILER=pgcc OPENMP=y
matrix:
  exclude:
    - os: linux
      env: COMPILER=clang
    - os: osx
      env: COMPILER=clang-3.7
    - os: osx
      env: COMPILER=clang-3.6 ASAN=y UBSAN=y
    - os: osx
      env: COMPILER=gcc-5 UBSAN=y
    - os: osx
      env: COMPILER=gcc-5 CSTD=11 UBSAN=y
    - os: osx
      env: COMPILER=gcc-4.9 ASAN=y UBSAN=y
    - os: osx
      env: COMPILER=gcc-4.8 ASAN=y
    - os: osx
      env: COMPILER=gcc-4.6
    - os: osx
      env: COMPILER=gcc-4.4
    - os: osx
      env: COMPILER=clang-3.5 ASAN=y UBSAN=y
    - os: osx
      env: COMPILER=clang-3.4 ASAN=y UBSAN=y
    - os: osx
      env: COMPILER=x86_64-w64-mingw32-gcc EXTENSION=".exe"
    - os: osx
      env: COMPILER=i686-w64-mingw32-gcc EXTENSION=".exe"
    - os: osx
      env: COMPILER=pgcc OPENMP=y
before_install:
 - ./.travis-install-compiler.sh
script:
 - make CC="${COMPILER}" AGGRESSIVE_WARNINGS=y EXTENSION="${EXTENSION}" OPENMP="${OPENMP}" ASAN="${ASAN}" UBSAN="${UBSAN}"
 # Installing Wine wants to pull in the graphical stack, so we can't
 # run the test for mingw.
 - if [ x"$EXTENSION" = "x" ]; then make test; fi
notifications:
  email: false
